runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /static
  static_dir: static
- url: /.*
  script: main.app
- url: /add/.*
  script: main.app
  login: required
  auth_fail_action: redirect
- url: /borrow/.*
  script: main.app
  login: required
  auth_fail_action: redirect
- url: /loan/.*
  script: main.app
  login: required
  auth_fail_action: redirect

libraries:
- name: ssl
  version: 2.7.11
